# Generated by Django 5.1.2 on 2024-10-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
